(function() {var implementors = {};
implementors['time'] = ["<a class='stability Unmarked' title='No stability level'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.Sub.html' title='core::ops::Sub'>Sub</a>&lt;<a class='struct' href='time/struct.Timespec.html' title='time::Timespec'>Timespec</a>, <a class='struct' href='http://doc.rust-lang.org/nightly/std/time/duration/struct.Duration.html' title='std::time::duration::Duration'>Duration</a>&gt; for <a class='struct' href='time/struct.Timespec.html' title='time::Timespec'>Timespec</a>",];
implementors['libgit2-sys'] = ["<a class='stability Unmarked' title='No stability level'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.Sub.html' title='core::ops::Sub'>Sub</a>&lt;<a class='struct' href='libgit2-sys/struct.git_revparse_mode_t.html' title='libgit2-sys::git_revparse_mode_t'>git_revparse_mode_t</a>, <a class='struct' href='libgit2-sys/struct.git_revparse_mode_t.html' title='libgit2-sys::git_revparse_mode_t'>git_revparse_mode_t</a>&gt; for <a class='struct' href='libgit2-sys/struct.git_revparse_mode_t.html' title='libgit2-sys::git_revparse_mode_t'>git_revparse_mode_t</a>",];
implementors['git2'] = ["<a class='stability Unmarked' title='No stability level'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.Sub.html' title='core::ops::Sub'>Sub</a>&lt;<a class='struct' href='git2/struct.CredentialType.html' title='git2::CredentialType'>CredentialType</a>, <a class='struct' href='git2/struct.CredentialType.html' title='git2::CredentialType'>CredentialType</a>&gt; for <a class='struct' href='git2/struct.CredentialType.html' title='git2::CredentialType'>CredentialType</a>","<a class='stability Unmarked' title='No stability level'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.Sub.html' title='core::ops::Sub'>Sub</a>&lt;<a class='struct' href='git2/struct.IndexAddOption.html' title='git2::IndexAddOption'>IndexAddOption</a>, <a class='struct' href='git2/struct.IndexAddOption.html' title='git2::IndexAddOption'>IndexAddOption</a>&gt; for <a class='struct' href='git2/struct.IndexAddOption.html' title='git2::IndexAddOption'>IndexAddOption</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
